### ISSUE TITLE
How to find a translated RFC

### ISSUE THREAD

**Issue by weihanglo** [rust-tw/rfcs-tw#3]
As a reader,  all RFCs look the same in the sidebar. How to identify that a RFC has a Chinese version? Perhaps add a prefix emoji like following would help:

- 2341-const-locals
- ✅ 2342-const-control-flow
- 2344-const-looping
- 2345-const-panic

cc @CYBAI @wusyong

**Comment by CYBAI** [comment]
I will propose to have a separated folder which might be clearer and it can be toggled to open in mdBook directly 👀 

(btw, I'm wondering if it's good to have some triage labels so that we can find some issues quicker? this is off-topic to this issue though)

**Comment by wusyong** [comment]
People who visit this book are looking for translated pages. Perhaps just remove all untranslated pages and leave some notes on the front page to tell them feel free to open a PR or issue if the RFCs they looking for aren't translated yet.

**Comment by weihanglo** [comment]
Fixed by 31eae2d2c81135febbd940ea37c076d1590a7ae6
